flowchart TB
 %% Entorno Externo del Sistema Educativo
subgraph Entorno
  Estudiantes[Estudiantes]
  Docentes[Docentes]
  Padres[Padres]
  Gobierno[Gobierno]
  Sociedad[Sociedad / Cultura / Tecnología]
end

 %% Comportamiento del Sistema
subgraph Comportamiento
  A[Entradas: Estudiantes, Programas, Recursos, Normativas, Tecnología]
  B[Procesos: Enseñanza, Evaluación, Desarrollo personal, Interacción social]
  C[Salidas: Aprendizajes, Certificaciones, Habilidades]
  D[Retroalimentación: Resultados académicos, Indicadores de desempeño,]
end

 %% Flujo del Sistema
Estudiantes --> A
Docentes --> A
Padres --> A
Gobierno --> A
Sociedad --> A
A --> B
B --> C
C --> D

 %% Retroalimentación del Proceso
D --> B

 %% Impacto de la Salida en el Entorno
C --> Estudiantes
C --> Sociedad